### ISSUE TITLE
Class vs Instance variable __pin

### ISSUE THREAD

**Issue by ericsalim** [flipsee/sensortest#1]
File: sensortest/dht/dht11.py

...

class DHT11:
    'DHT11 sensor reader class for Raspberry'

```
__pin = 0

def __init__(self, pin):
    self.__pin = pin
```

...

__pin = 0 means static class variable.
self.__pin means instance variable.

Is this a bug?

**Comment by flipsee** [comment]
both is pointing at the same thing

class wut:
    _pin=0

```
def __init__(self, pin = -1):
    if pin > -1:
        self._pin = pin

def setpin(self, pin):
    if pin > -1:
        self._pin = pin

def getpin(self):
    print(str(self._pin))
```

wut1 = wut()
wut1.getpin()
print(str(wut1._pin))

wut2 = wut(15)
wut2.getpin()
print(str(wut2._pin))
